name: MinecraftGame
version: ${project.version}
main: mproject.dontknow.Dontknow
api-version: 1.13
commands:
  Truce:
    description: Allows for trucing in game
  Setsolo:
    description: Sets a solo player for game
