name: MinecraftGame
version: 1.0-SNAPSHOT
main: mproject.dontknow.Dontknow
description: this is a description
api-version: 1.13
commands:
  Truce:
    description: Allows for trucing in game
  Setsolo:
    description: Sets a solo player for game
